name: ${name}
version: ${version}
main: com.LRFLEW.bukkit.book.BMPlugin
author: [LRFLEW, ProjectInfinity]
description: An advanced book management plugin
softdepend: [Vault]
commands:
  unsign:
    description: Unsigns Written Books
    aliases: us
    permission: bookmanager.unsign
    usage: "Hold a Written Book and use: /<command>"
    permission-message: You don't have permission to unsign books
  rnbook:
    description: Renames Written Books
    aliases: rb
    permission: bookmanager.rnbook
    usage: "Hold a Written Book and use: /<command> <name>"
    permission-message: You don't have permission to rename books
  rnauth:
    description: Changes the Author Name for Written Books
    aliases: ra
    permission: bookmanager.rnauth
    usage: "Hold a Written Book and use: /<command> <name>"
    permission-message: You don't have permission to change the author name of books
  copybook:
    description: Copies Written Books
    aliases: cb
    permission: bookmanager.copy
    usage: "Hold a Written Book and use: /<command> [amount]"
    permission-message: You don't have permission to copy books
  savebook:
    description: Saves Written Books in the plugin folder
    aliases: st
    permission: bookmanager.savebook
    usage: "Hold a Written Book and use: /<command> <save name>"
    permission-message: You don't have permission to use that command
  loadbook:
    description: Loads Written Books in the plugin folder
    aliases: lb
    permission: bookmanager.loadbook
    usage: "usage: /<command> <save name>"
    permission-message: You don't have permission to use that command
  deletebook:
    description: Deletes a saved book
    permission: bookmanager.deletebook
    usage: "usage: /<command> <save name>"
    permission-message: You don't have permission to use that command
  listbooks:
    description: Lists all saved books you can access
    aliases: ltb
    permission: bookmanager.listbooks
    usage: "usage: /<command>"
    permission-message: You don't have permission to use that command

permissions:
  bookmanager.unsign:
    description: allows player to use /unsign on their own books
    default: true
  bookmanager.unsign.other:
    description: allows player to use /unsign on other player's books
    default: op
    children:
      bookmanager.unsign: true
  bookmanager.rnbook:
    description: allows player to use /rnbook on their own books
    default: true
  bookmanager.rnbook.other:
    description: allows player to use /rnbook on other player's books
    default: op
    children:
      bookmanager.rnbook: true
  bookmanager.rnauth:
    description: allows player to use /rnauth
    default: op
  bookmanager.copy:
    description: allows player to use /copybook
    default: true
  bookmanager.copy.free:
    description: allows player to use /copybook without extra materials
    default: op
    children:
      bookmanager.copy: true
  bookmanager.copy.other:
    description: allows player to use /copybook on other player's books
    default: op
    children:
      bookmanager.copy: true
  bookmanager.savebook:
    description: allows player to use /savebook
    default: op
  bookmanager.loadbook:
    description: allows player to use /loadbook
    default: true
  bookmanager.loadbook.free:
    description: allows player to use /loadbook free
    default: op
    children:
      bookmanager.loadbook: true
  bookmanager.loadbook.all:
    description: allows player to use /loadbook on all saved books
    default: op
    children:
      bookmanager.loadbook: true
  bookmanager.deletebook:
    description: allows player to use /deletebook
    default: op
  bookmanager.listbooks:
    description: allows player to use /listbooks
    default: true
    
  bookmanager.none:
    description: removes all permissions from player for BookManager
    children:
      bookmanager.unsign: false
      bookmanager.unsign.other: false
      bookmanager.rnbook: false
      bookmanager.rnbook.other: false
      bookmanager.rnauth: false
      bookmanager.copy: false
      bookmanager.copy.free: false
      bookmanager.savebook: false
      bookmanager.loadbook: false
      bookmanager.loadbook.free: false
      bookmanager.loadbook.all: false
      bookmanager.deletebook: false
      bookmanager.listbooks: false
  bookmanager.default:
    description: gives player control over their own books only
    children:
      bookmanager.unsign: true
      bookmanager.unsign.other: false
      bookmanager.rnbook: true
      bookmanager.rnbook.other: false
      bookmanager.rnauth: false
      bookmanager.copy: true
      bookmanager.copy.free: false
      bookmanager.savebook: false
      bookmanager.loadbook: true
      bookmanager.loadbook.free: false
      bookmanager.loadbook.all: false
      bookmanager.deletebook: false
      bookmanager.listbooks: true
  bookmanager.admin:
    description: gives player control over any book
    children:
      bookmanager.unsign.other: true
      bookmanager.rnbook.other: true
      bookmanager.rnauth: true
      bookmanager.copy.free: true
      bookmanager.savebook: true
      bookmanager.loadbook.free: true
      bookmanager.loadbook.all: true
      bookmanager.deletebook: true
      bookmanager.listbooks: true
      bookmanager.deletebook: true
      bookmanager.listbooks: true